services:
  mortgage-manager:
    build: .
    container_name: mortgage-manager
    #ports:
    #  - "8080:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mortgage-manager.rule=Host(`mortgage.personal.valla`)"
      - "traefik.http.services.mortgage-manager.loadbalancer.server.port=80"
    restart: unless-stopped
